// Generated by scripts/generate-mastery-kits.mjs. Do not edit by hand.
// Uses only Node.js built-ins and never reads a reference solution directory.

import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { pathToFileURL } from "node:url";
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const candidateRoot = existsSync(join(projectRoot, "starter"))
  ? join(projectRoot, "starter")
  : projectRoot;
const read = (path) => readFileSync(join(candidateRoot, path), "utf8");

const instructions = read("CLAUDE.md");
const packageJson = JSON.parse(read("package.json"));
const initials = await import(pathToFileURL(join(candidateRoot, "src/initials.js")).href + "?mastery=" + Date.now());

test("provides concise, project-specific operating context", () => {
  const lines = instructions.trim().split(/\r?\n/);
  assert.ok(lines.length <= 30, "keep CLAUDE.md under 30 lines");
  assert.match(instructions, /initial|name/i);
  assert.match(instructions, /\bsrc\/?\b/i);
  assert.match(instructions, /\btest\/?\b/i);
  assert.match(instructions, /npm test/);
  assert.doesNotMatch(instructions, /make the code good|todo/i);
});

test("states concrete safety limits and a verifiable definition of done", () => {
  assert.match(instructions, /(?:do not|forbid|no)\b[^\n]*(?:dependenc|package)/i);
  assert.match(instructions, /(?:do not|forbid|no)\b[^\n]*network/i);
  assert.match(instructions, /(?:do not|forbid|no)\b[^\n]*(?:weaken|hide|modify)[^\n]*(?:test|fixture)|(?:test|fixture)[^\n]*(?:weaken|hide)/i);
  assert.match(instructions, /changed files?/i);
  assert.match(instructions, /test (?:output|evidence)|test evidence|report[^\n]*test/i);
  assert.match(instructions, /uncertaint/i);
  assert.doesNotMatch(instructions, /(?:token|password|secret)\s*[:=]\s*\S+/i);
  assert.doesNotMatch(instructions, new RegExp("/(?:Users|home)/[^\\s]+"));
});

test("retains the dependency-free implementation baseline", () => {
  assert.equal(packageJson.scripts.test, "node --test");
  assert.equal(Object.keys(packageJson.dependencies ?? {}).length, 0);
  assert.equal(Object.keys(packageJson.devDependencies ?? {}).length, 0);
  assert.equal(initials.toInitials("  safe   small steps "), "SSS");
});
